---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Run the specified shell command
      command: 'ls -lrth'
      register: result
      changed_when: False

    - name: Display the outcome
      debug:
        msg: '{{result}}'

